### ISSUE TITLE
How to convert spark dataframe to rddlist

### ISSUE THREAD

**Issue by ZJUguquan** [clarkfitzg/rddlist#2]
Hi,
your work is very nice!
I want to know how to combine functions in the two packages `sparklyr` and `rddlist`. e.g. How can I convert a sparklyr dataframe to an rddlist so that I can use the rdd apply functions? Or rddlist to dataframe?

Waiting for your reply~

**Comment by clarkfitzg** [comment]
Thank you. There's not much compatibility between the two packages- `sparklyr` was only used for the low level connections. It would take some serious work to do this conversion.

One possible way is to preprocess the data into files containing the elements of the list (using sparklyr or hive or Pyspark ...), then read those using an rdd apply function.

**Comment by ZJUguquan** [comment]
okey, thank you anyway~
